
export const ACTION_ADD = 'ACTION_ADD'
export const ACTION_DELETE = 'ACTION_DELETE'
export const ACTION_SELECT = 'ACTION_SELECT'
export const ACTION_DESELECT = 'ACTION_DESELECT'
export const ACTION_CHANGE_PLACE = "ACTION_CHANGE_PLACE"
export const PLACE_NAME_CLEAR = "ACTION_PLACE_CLAER"
